In [1]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.svm import SVC

In [2]:
data=pd.read_csv("./glass.csv")
data.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [3]:
x=data.drop('Type',axis=1)
y=data.Type

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)



In [6]:
linear = svm.SVC(kernel = 'linear')
linear.fit(x_train,y_train)

SVC(kernel='linear')

In [7]:
print(linear.n_support_)

[1 3 2 4 3 2]


In [8]:
y_pre = linear.predict(x_test)

In [9]:
from sklearn.metrics import accuracy_score


print("accuracy : ",accuracy_score(y_test,y_pre))

accuracy :  0.9846153846153847


In [10]:
from sklearn.metrics import classification_report
print("/report")
print(classification_report(y_test,y_pre))

/report
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        22
           2       1.00      0.96      0.98        24
           3       0.88      1.00      0.93         7
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         8

    accuracy                           0.98        65
   macro avg       0.98      0.99      0.99        65
weighted avg       0.99      0.98      0.98        65



In [11]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pre))

[[22  0  0  0  0  0]
 [ 0 23  1  0  0  0]
 [ 0  0  7  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  8]]


In [12]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

In [14]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [15]:
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)
y_pred3=model3.predict(x_test)

In [16]:
print("predicted by model1",accuracy_score(y_test,y_pred1))
print("predicted by model2",accuracy_score(y_test,y_pred2))
print("predicted by model3",accuracy_score(y_test,y_pred3))

predicted by model1 0.6307692307692307
predicted by model2 0.9692307692307692
predicted by model3 0.8923076923076924
